preload = /home/joe/Pictures/wallpapers/Gemini_Generated_Image_z89wkuz89wkuz89w.png
wallpaper = eDP-1,/home/joe/Pictures/wallpapers/Gemini_Generated_Image_z89wkuz89wkuz89w.png
wallpaper = eDP-1,/home/joe/Pictures/wallpapers/Gemini_Generated_Image_z89wkuz89wkuz89w.png
splash = false
